<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    کوویدکاوی
</font>
</h1>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در این تمرین می‌خواهیم داده‌های مربوط به وضعیت کووید-۱۹ در کشورهای مختلف جهان در یک روز از سال ۲۰۲۰ را کمی تحلیل کنیم و با پاسخ دادن به پرسش‌هایی از آن با کتابخانه‌ی <code>pandas</code> بیشتر کار کنیم.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مجموعه‌داده‌
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
ابتدا داده‌ها را از فایل <code>covid19-11-10-2020.csv</code> بخوانید و در متغیر <code>covid_data</code> ذخیره کنید.
</font>
</p>

In [1]:
import pandas as pd

In [2]:
covid_data = pd.read_csv("covid19-11-10-2020.csv")
covid_data.head()

,Unnamed: 0,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,0,NaN,NaN,NaN,Afghanistan,2020-11-11 05:25:30,33.93911,67.709953,42297,1574,34954.0,5769.0,Afghanistan,108.653487,3.721304
1,1,NaN,NaN,NaN,Albania,2020-11-11 05:25:30,41.15330,20.168300,25294,579,12353.0,12362.0,Albania,878.935298,2.289080
2,2,NaN,NaN,NaN,Algeria,2020-11-11 05:25:30,28.03390,1.659600,63446,2077,42626.0,18743.0,Algeria,144.685270,3.273650
3,3,NaN,NaN,NaN,Andorra,2020-11-11 05:25:30,42.50630,1.521800,5477,75,4405.0,997.0,Andorra,7088.591212,1.369363
4,4,NaN,NaN,NaN,Angola,2020-11-11 05:25:30,-11.20270,17.873900,12816,308,6036.0,6472.0,Angola,38.994388,2.403246

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
    <font face="vazir" size=3>
        همان‌طور که احتمالاً دیده‌اید، این مجموعه‌داده دارای ۱۴ ویژگی/ستون است که به معرفی برخی از آن‌ها که مهم‌ترند می‌پردازیم. البته که شما باید تشخیص بدهید که در هر سوال کدام موارد به کار می‌آیند.
        <br>
       - ستون  <code>Country_Region</code>: مشخص است که نام کشور یا منطقه را مشخص می‌کند. دقت کنید که شاید لازم باشد بررسی کنید که آیا تعداد سطرها با تعداد کشورها برابر است و به بیان دیگر به ازای هر منطقه یا کشور فقط یک سطر دیتا وجود دارد یا خیر.
        <br>
        - ستون‌های <code>Long</code> و <code>Lat</code>: طول و عرض جفرافیایی کشور/منطقه را بیان می‌کند.
        <br>
        - ستون <code>Confirmed</code>: تعداد موارد تاییدشده‌ی ابتلا به ویروس
        <br>
        - ستون <code>Deaths</code>: تعداد موارد فوت‌شده
        <br>
        - ستون <code>Recovered</code>: تعداد موارد بهبودیافته
        <br>
        - ستون <code>Active</code>: تعداد موارد فعال (که از تفاضل مجموع فوتی‌ها و بهبودیافتگان از موارد تایید شده نیز به‌دست می‌آید.)
        <br>
        - ستون <code>Incident_Rate</code>: بیانگر تعداد موارد در هر ۱۰۰۰۰۰ نفر است.
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<b style="color:red">نکته‌:</b>
در هر سوال که از شما خواسته‌شده پاسخ را در قالب فایلی با فرمت <code>csv</code> ذخیره کنید، لازم نیست نام ستون‌ها را ذخیره کنید (به بیان دیگر لازم نیست  <code>header</code> داشته باشند).
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت اول‌
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
     در ابتدا می‌خواهیم ببینیم ۱۰ کشور با بیشترین تعداد موارد  کدام‌اند. برای این کار می‌توانیم از
ستون  <code>Incident_Rate</code> استفاده کنیم. البته برای این‌که به‌نوعی مجموع تقریبی موارد را از این ستون محاسبه کنیم می‌توانیم از متد <code>apply</code>  استفاده کنیم و ستونی جدید به نام <code>Total_Cases</code> اضافه کنیم که از حاصل ضرب ۱۰۰۰۰۰ در مقادیر ستون <code>Incident_Rate</code> توسط تابع <code>apply</code> به‌دست می‌آیند.
<br>
پاسخ شما باید دارای ۱۰ ردیف و ۲ ستون باشد که نام کشور/منطقه و <code>Total_Cases</code> را شامل می‌شود و آن را در فایلی به نام <code>top10cases.csv</code> ذخیره کنید. 
</font>
</p>

In [3]:
df_inc = covid_data[["Country_Region" , "Incident_Rate"]].copy()
df_inc

      Country_Region  Incident_Rate
0        Afghanistan     108.653487
1            Albania     878.935298
2            Algeria     144.685270
3            Andorra    7088.591212
4             Angola      38.994388
...              ...            ...
3993         Ukraine       0.000000
3994           Nauru       0.000000
3995     New Zealand       0.000000
3996          Tuvalu       0.000000
3997  United Kingdom       0.000000

[3998 rows x 2 columns]

In [4]:
func = lambda x: x * 100000

In [5]:
df_inc["Total_Cases"] = df_inc["Incident_Rate"].apply(func)
df_inc

      Country_Region  Incident_Rate   Total_Cases
0        Afghanistan     108.653487  1.086535e+07
1            Albania     878.935298  8.789353e+07
2            Algeria     144.685270  1.446853e+07
3            Andorra    7088.591212  7.088591e+08
4             Angola      38.994388  3.899439e+06
...              ...            ...           ...
3993         Ukraine       0.000000  0.000000e+00
3994           Nauru       0.000000  0.000000e+00
3995     New Zealand       0.000000  0.000000e+00
3996          Tuvalu       0.000000  0.000000e+00
3997  United Kingdom       0.000000  0.000000e+00

[3998 rows x 3 columns]

In [13]:
all_countries = df_inc.groupby("Country_Region" , as_index=False)["Total_Cases"].sum().sort_values(by="Total_Cases", ascending=False)
top10= all_countries.head(10)
top10

    Country_Region   Total_Cases
185             US  1.060653e+12
146         Russia  1.084148e+10
24          Brazil  9.817550e+09
140           Peru  6.967909e+09
38        Colombia  6.661217e+09
166          Spain  5.766248e+09
36           Chile  4.348631e+09
86           Italy  3.359897e+09
187        Ukraine  3.171402e+09
80           India  3.116931e+09

In [14]:
top10.to_csv("top10cases.csv" , header=False)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت دوم
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در ادامه می‌خواهیم ببینیم چه کشورهایی بیشترین نرخ ریکاوری را داشته‌اند. بدین منظور قصد داریم شاخصی تعریف کنیم تحت عنوان <code>Recovery_Rate</code> که از حاصل تقسیم تعداد بهبودیافتگان به تعداد موارد تایید شده بدست می‌آید. البته در ابتدا قصد داریم کشورها/مناطقی که موارد تایید شده، فوت شده و بهبودیافته‌ی آن‌ها صفر گزارش شده است را درنظر نگیریم.
پس ردیف‌هایی که مقدار هر سه ستون <code>Confirmed</code>، <code>Deaths</code> و <code>Recovered</code> آن‌ها صفر است را از دیتافریم اصلی حذف کنید. سپس می‌خواهیم در بین کشورهایی که موارد تاییدشده به ابتلای آنها از میانه‌ی این شاخص بیشتر است ببینیم کدام‌شان نرخ ریکاوری بهتری دارد. بدین منظور در بین این کشورها، فهرست آنهایی که نرخ ریکاوری آنها از میانگین این نرخ برای همه کشورها بیشتر است را به صورت نزولی  
 در فایلی به نام <code>recovery_rate.csv</code> ذخیره کنید. پس فیلتر اولیه بر اساس میانه‌ی تعداد موارد تایید شده‌ی مبتلایان و فیلتر دوم بر اساس میانگین نرخ ریکاوری است.
<br>
توجه داشته باشید که فایل شما باید شامل دو ستون باشد که به ترتیب نام کشور/منطقه و نرخ ریکاوری باشد و ترتیب آن به صورت نزولی بر اساس نرخ ریکاوری.
</font>
</p>

In [16]:
data = pd.read_csv("covid19-11-10-2020.csv")
data.head()

,Unnamed: 0,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,0,NaN,NaN,NaN,Afghanistan,2020-11-11 05:25:30,33.93911,67.709953,42297,1574,34954.0,5769.0,Afghanistan,108.653487,3.721304
1,1,NaN,NaN,NaN,Albania,2020-11-11 05:25:30,41.15330,20.168300,25294,579,12353.0,12362.0,Albania,878.935298,2.289080
2,2,NaN,NaN,NaN,Algeria,2020-11-11 05:25:30,28.03390,1.659600,63446,2077,42626.0,18743.0,Algeria,144.685270,3.273650
3,3,NaN,NaN,NaN,Andorra,2020-11-11 05:25:30,42.50630,1.521800,5477,75,4405.0,997.0,Andorra,7088.591212,1.369363
4,4,NaN,NaN,NaN,Angola,2020-11-11 05:25:30,-11.20270,17.873900,12816,308,6036.0,6472.0,Angola,38.994388,2.403246

In [17]:
data = data[~((data['Deaths'] == 0) & (data['Confirmed'] == 0) & (data['Recovered'] == 0))]
data.head()

,Unnamed: 0,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,0,NaN,NaN,NaN,Afghanistan,2020-11-11 05:25:30,33.93911,67.709953,42297,1574,34954.0,5769.0,Afghanistan,108.653487,3.721304
1,1,NaN,NaN,NaN,Albania,2020-11-11 05:25:30,41.15330,20.168300,25294,579,12353.0,12362.0,Albania,878.935298,2.289080
2,2,NaN,NaN,NaN,Algeria,2020-11-11 05:25:30,28.03390,1.659600,63446,2077,42626.0,18743.0,Algeria,144.685270,3.273650
3,3,NaN,NaN,NaN,Andorra,2020-11-11 05:25:30,42.50630,1.521800,5477,75,4405.0,997.0,Andorra,7088.591212,1.369363
4,4,NaN,NaN,NaN,Angola,2020-11-11 05:25:30,-11.20270,17.873900,12816,308,6036.0,6472.0,Angola,38.994388,2.403246

In [18]:
data.shape

(3950, 15)

In [23]:
df = data[["Country_Region" ,"Confirmed" , "Recovered"]].copy()
df

      Country_Region  Confirmed  Recovered
0        Afghanistan      42297    34954.0
1            Albania      25294    12353.0
2            Algeria      63446    42626.0
3            Andorra       5477     4405.0
4             Angola      12816     6036.0
...              ...        ...        ...
3983        Malaysia       3213     3041.0
3984        Malaysia       1053      544.0
3985        Malaysia        180      148.0
3990  United Kingdom        659        0.0
3991  United Kingdom        279        0.0

[3950 rows x 3 columns]

In [24]:
df = df.groupby("Country_Region" , as_index=False)[["Recovered" , "Confirmed"]].sum()
df

         Country_Region  Recovered  Confirmed
0           Afghanistan    34954.0      42297
1               Albania    12353.0      25294
2               Algeria    42626.0      63446
3               Andorra     4405.0       5477
4                Angola     6036.0      12816
..                  ...        ...        ...
185             Vietnam     1087.0       1226
186  West Bank and Gaza    51425.0      59422
187               Yemen     1375.0       2063
188              Zambia    16019.0      16997
189            Zimbabwe     8040.0       8610

[190 rows x 3 columns]

In [26]:
df["Recovery_Rate"] = df["Recovered"] / df["Confirmed"]
df

         Country_Region  Recovered  Confirmed  Recovery_Rate
0           Afghanistan    34954.0      42297       0.826394
1               Albania    12353.0      25294       0.488377
2               Algeria    42626.0      63446       0.671847
3               Andorra     4405.0       5477       0.804272
4                Angola     6036.0      12816       0.470974
..                  ...        ...        ...            ...
185             Vietnam     1087.0       1226       0.886623
186  West Bank and Gaza    51425.0      59422       0.865420
187               Yemen     1375.0       2063       0.666505
188              Zambia    16019.0      16997       0.942460
189            Zimbabwe     8040.0       8610       0.933798

[190 rows x 4 columns]

In [27]:
median_confirmed = df["Confirmed"].median()
mean_recovery = df["Recovery_Rate"].mean()
median_confirmed , mean_recovery

(23932.0, 0.7267428587109472)

In [28]:
above_median_counts = df[df["Confirmed"] > median_confirmed]
above_median_counts

           Country_Region  Recovered  Confirmed  Recovery_Rate
0             Afghanistan    34954.0      42297       0.826394
1                 Albania    12353.0      25294       0.488377
2                 Algeria    42626.0      63446       0.671847
6               Argentina  1081897.0    1262476       0.856964
7                 Armenia    66835.0     108687       0.614931
..                    ...        ...        ...            ...
179  United Arab Emirates   139701.0     144385       0.967559
180        United Kingdom     3010.0    1237166       0.002433
182            Uzbekistan    66194.0      69027       0.958958
184             Venezuela    90359.0      95445       0.946713
186    West Bank and Gaza    51425.0      59422       0.865420

[95 rows x 4 columns]

In [34]:
above_recovery_counts = above_median_counts[above_median_counts["Recovery_Rate"] > mean_recovery]
above_recovery_counts

           Country_Region  Recovered  Confirmed  Recovery_Rate
0             Afghanistan    34954.0      42297       0.826394
6               Argentina  1081897.0    1262476       0.856964
8               Australia    22298.0      27671       0.805826
10             Azerbaijan    50009.0      67392       0.742061
12                Bahrain    81415.0      83811       0.971412
13             Bangladesh   341416.0     423620       0.805949
15                Belarus    91646.0     108300       0.846223
20                Bolivia   115199.0     142664       0.807485
23                 Brazil  5183970.0    5726227       0.905303
27                  Burma    47411.0      63241       0.749688
32                 Canada   224912.0     277808       0.809595
35                  Chile   500142.0     523907       0.954639
36                  China    86421.0      97902       0.882730
37               Colombia   980866.0    1155356       0.848973
43                Croatia    54854.0      70243       0.780918
47                Denmark    42759.0      57472       0.743997
51     Dominican Republic   108765.0     131131       0.829438
52                Ecuador   154956.0     175711       0.881880
53                  Egypt   100540.0     109654       0.916884
54            El Salvador    31172.0      35684       0.873557
65                Georgia    47390.0      63650       0.744540
67                  Ghana    47843.0      49302       0.970407
70              Guatemala   102140.0     112129       0.910915
79                  India  8013783.0    8636011       0.927950
80              Indonesia   375741.0     444348       0.845601
81                   Iran   530694.0     703288       0.754590
82                   Iraq   434665.0     505310       0.860195
84                 Israel   308145.0     320811       0.960519
87                  Japan    98487.0     110449       0.891697
89             Kazakhstan   137590.0     156451       0.879445
91           Korea, South    25266.0      27799       0.908882
93                 Kuwait   124156.0     133381       0.930837
94             Kyrgyzstan    55306.0      64360       0.859323
114                Mexico   824355.0     978531       0.842441
115               Moldova    64826.0      83592       0.775505
119               Morocco   216851.0     265165       0.817796
122                 Nepal   160577.0     199760       0.803850
127               Nigeria    60333.0      64336       0.937780
130                  Oman   109330.0     118884       0.919636
131              Pakistan   320065.0     348184       0.919241
132                Panama   119707.0     141302       0.847171
135                  Peru   850670.0     923527       0.921110
136           Philippines   361919.0     399749       0.905366
139                 Qatar   131733.0     134663       0.978242
141                Russia  1341868.0    1802762       0.744340
148          Saudi Arabia   338281.0     351455       0.962516
153             Singapore    57985.0      58073       0.998485
158          South Africa   683194.0     740254       0.922918
175                Turkey   342501.0     399360       0.857625
179  United Arab Emirates   139701.0     144385       0.967559
182            Uzbekistan    66194.0      69027       0.958958
184             Venezuela    90359.0      95445       0.946713
186    West Bank and Gaza    51425.0      59422       0.865420

In [36]:
result = above_recovery_counts[["Country_Region" ,"Recovery_Rate"]].sort_values(by= "Recovery_Rate", ascending=False)
result

           Country_Region  Recovery_Rate
153             Singapore       0.998485
139                 Qatar       0.978242
12                Bahrain       0.971412
67                  Ghana       0.970407
179  United Arab Emirates       0.967559
148          Saudi Arabia       0.962516
84                 Israel       0.960519
182            Uzbekistan       0.958958
35                  Chile       0.954639
184             Venezuela       0.946713
127               Nigeria       0.937780
93                 Kuwait       0.930837
79                  India       0.927950
158          South Africa       0.922918
135                  Peru       0.921110
130                  Oman       0.919636
131              Pakistan       0.919241
53                  Egypt       0.916884
70              Guatemala       0.910915
91           Korea, South       0.908882
136           Philippines       0.905366
23                 Brazil       0.905303
87                  Japan       0.891697
36                  China       0.882730
52                Ecuador       0.881880
89             Kazakhstan       0.879445
54            El Salvador       0.873557
186    West Bank and Gaza       0.865420
82                   Iraq       0.860195
94             Kyrgyzstan       0.859323
175                Turkey       0.857625
6               Argentina       0.856964
37               Colombia       0.848973
132                Panama       0.847171
15                Belarus       0.846223
80              Indonesia       0.845601
114                Mexico       0.842441
51     Dominican Republic       0.829438
0             Afghanistan       0.826394
119               Morocco       0.817796
32                 Canada       0.809595
20                Bolivia       0.807485
13             Bangladesh       0.805949
8               Australia       0.805826
122                 Nepal       0.803850
43                Croatia       0.780918
115               Moldova       0.775505
81                   Iran       0.754590
27                  Burma       0.749688
65                Georgia       0.744540
141                Russia       0.744340
47                Denmark       0.743997
10             Azerbaijan       0.742061

In [37]:
result.to_csv("recovery_rate.csv" , header=False)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت سوم
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
اکنون می‌خواهیم اوضاع سایر کشورها را با کشور خودمان مقایسه‌ای کنیم! از این روی می‌خواهیم ببینیم کدام کشورها با وجود این‌که مبتلایان بیشتری از ما داشته‌اند، مرگ و میر کمتری ثبت کرده‌اند.
<br>
پاسخ را در فایلی به نام <code> vsiran.csv </code> ذخیره کنید. فایل پاسخ باید حاوی ۴ ستون باشد که نام کشور/منطقه، موارد تایید شده، موارد فوت‌شده و موارد بهبودیافته را به‌صورت نزولی بر اساس تعداد موارد تایید شده در بر داشته باشد.
</font>
</p>

In [39]:
data = pd.read_csv("covid19-11-10-2020.csv")

In [40]:
iran_confirmed = data[data['Country_Region'].str.contains('Iran', na=False)]['Confirmed'].sum()
iran_confirmed

703288

In [41]:
iran_death = data[data['Country_Region'].str.contains('Iran', na=False)]['Deaths'].sum()
iran_death

39202

In [42]:
other_couns = data.groupby('Country_Region', as_index=False)[['Confirmed', 'Deaths', 'Recovered']].sum()
other_couns

           Country_Region  Confirmed  Deaths  Recovered
0             Afghanistan      42297    1574    34954.0
1                 Albania      25294     579    12353.0
2                 Algeria      63446    2077    42626.0
3                 Andorra       5477      75     4405.0
4                  Angola      12816     308     6036.0
..                    ...        ...     ...        ...
195    West Bank and Gaza      59422     533    51425.0
196  Winter Olympics 2022          0       0        0.0
197                 Yemen       2063     601     1375.0
198                Zambia      16997     350    16019.0
199              Zimbabwe       8610     255     8040.0

[200 rows x 4 columns]

In [43]:
better_counts = other_couns[(other_couns['Confirmed'] > iran_confirmed) & (other_couns['Deaths'] < iran_death)]
better_counts

    Country_Region  Confirmed  Deaths  Recovered
7        Argentina    1262476   34183  1081897.0
38        Colombia    1155356   33128   980866.0
146         Russia    1802762   30899  1341868.0
164   South Africa     740254   19951   683194.0

In [44]:
vsiran = better_counts.sort_values(by= "Confirmed" , ascending=False)
vsiran

    Country_Region  Confirmed  Deaths  Recovered
146         Russia    1802762   30899  1341868.0
7        Argentina    1262476   34183  1081897.0
38        Colombia    1155356   33128   980866.0
164   South Africa     740254   19951   683194.0

In [45]:
iran_death , iran_confirmed

(39202, 703288)

In [46]:
vsiran.to_csv("vsiran.csv" , header=False)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت چهارم
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در ادامه می‌خواهیم ادعای سخنگوی وزارت بهداشت کشوری را ارزیابی کنیم که ادعا می‌کند کشورش با توجه به آمار فوتی‌هایشان در این روز، جزو ۲۰ درصد برتر جهان است (هنوز در آن زمان عبارتی مثل «کشورهای برتر یک درصد جهان» کشف نشده بود :) ).
<br>
ما تعداد مرگ‌های گزارش‌شده را به تنهایی کافی نمی‌دانیم و فرض کنید برای راستی‌آزمایی این ادعا می‌خواهیم از شاخص ساده‌ای چون <b style="color:#0099cc">نسبت تعداد متوفیان به مبتلایان</b> استفاده کنیم. البته برای اینکه اینقدر هم دیگر ساده نباشد (!)، می‌خواهیم کشورهایی که مبتلایان تایید شده‌ی کمی در این روز داشته‌اند را در نظر نگیریم و برای این کار ۲۰ درصد کشورهایی که کمترین مبتلایان را داشته‌اند را نیز کنار می‌گذاریم و سپس شاخص مربوطه را برای کشورهای باقی‌مانده لحاظ می‌کنیم.
<br>
مقدار شاخص را در ستونی به نام <code>death_ratio</code> ذخیره کرده و
فهرست ۲۰ درصد برتر را به همراه مقدار شاخص ذکر شده در فایلی به نام 
    <code>20percent.csv</code> ذخیره کنید.

</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<b style="color:orange">توجه:</b>
آن دسته از ردیف‌هایی که مقدار ستون <code>Confirmed</code> آن‌ها برابر صفر است را در نظر نگرفته و حذف کنید.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<b style="color:green">راهنمایی:</b>
دیتافریم حاصل شامل ۳۰ ردیف خواهد بود.
</font>
</p>

In [47]:
df = pd.read_csv("covid19-11-10-2020.csv")
df.head()

,Unnamed: 0,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,0,NaN,NaN,NaN,Afghanistan,2020-11-11 05:25:30,33.93911,67.709953,42297,1574,34954.0,5769.0,Afghanistan,108.653487,3.721304
1,1,NaN,NaN,NaN,Albania,2020-11-11 05:25:30,41.15330,20.168300,25294,579,12353.0,12362.0,Albania,878.935298,2.289080
2,2,NaN,NaN,NaN,Algeria,2020-11-11 05:25:30,28.03390,1.659600,63446,2077,42626.0,18743.0,Algeria,144.685270,3.273650
3,3,NaN,NaN,NaN,Andorra,2020-11-11 05:25:30,42.50630,1.521800,5477,75,4405.0,997.0,Andorra,7088.591212,1.369363
4,4,NaN,NaN,NaN,Angola,2020-11-11 05:25:30,-11.20270,17.873900,12816,308,6036.0,6472.0,Angola,38.994388,2.403246

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3998 entries, 0 to 3997
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           3998 non-null   int64
 1   FIPS                 3265 non-null   float64
 2   Admin2               3270 non-null   object
 3   Province_State       3819 non-null   object
 4   Country_Region       3998 non-null   object
 5   Last_Update          3998 non-null   object
 6   Lat                  3912 non-null   float64
 7   Long_                3912 non-null   float64
 8   Confirmed            3998 non-null   int64
 9   Deaths               3998 non-null   int64
 10  Recovered            3997 non-null   float64
 11  Active               3997 non-null   float64
 12  Combined_Key         3998 non-null   object
 13  Incident_Rate        3912 non-null   float64
 14  Case_Fatality_Ratio  3947 non-null   float64
dtypes: float64(7), int64(3), object(5)
memory usage: 468.6+ KB

In [49]:
df_filtered = df[~(df["Confirmed"] == 0)]
df_filtered.head()

,Unnamed: 0,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,0,NaN,NaN,NaN,Afghanistan,2020-11-11 05:25:30,33.93911,67.709953,42297,1574,34954.0,5769.0,Afghanistan,108.653487,3.721304
1,1,NaN,NaN,NaN,Albania,2020-11-11 05:25:30,41.15330,20.168300,25294,579,12353.0,12362.0,Albania,878.935298,2.289080
2,2,NaN,NaN,NaN,Algeria,2020-11-11 05:25:30,28.03390,1.659600,63446,2077,42626.0,18743.0,Algeria,144.685270,3.273650
3,3,NaN,NaN,NaN,Andorra,2020-11-11 05:25:30,42.50630,1.521800,5477,75,4405.0,997.0,Andorra,7088.591212,1.369363
4,4,NaN,NaN,NaN,Angola,2020-11-11 05:25:30,-11.20270,17.873900,12816,308,6036.0,6472.0,Angola,38.994388,2.403246

In [60]:
all_couns = df_filtered.groupby("Country_Region", as_index=False)[["Confirmed" , "Deaths"]].sum().sort_values(by= "Confirmed")
all_couns

            Country_Region  Confirmed  Deaths
111       Marshall Islands          1       0
183                Vanuatu          1       0
104             MS Zaandam          9       2
156        Solomon Islands         16       0
143  Saint Kitts and Nevis         19       0
..                     ...        ...     ...
141                 Russia    1802762   30899
62                  France    1881171   42281
23                  Brazil    5726227  162922
79                   India    8636011  127571
176                     US   10331958  240316

[190 rows x 3 columns]

In [61]:
offset = int(len(all_couns) * 0.2)
offset

38

In [62]:
df_filtered = all_couns.iloc[offset:].copy()
df_filtered

    Country_Region  Confirmed  Deaths
187          Yemen       2063     601
152   Sierra Leone       2386      74
72   Guinea-Bissau       2419      43
172           Togo       2558      57
26    Burkina Faso       2582      67
..             ...        ...     ...
141         Russia    1802762   30899
62          France    1881171   42281
23          Brazil    5726227  162922
79           India    8636011  127571
176             US   10331958  240316

[152 rows x 3 columns]

In [63]:
df_filtered["death_ratio"] = df_filtered["Deaths"] / df_filtered["Confirmed"]
df_filtered

    Country_Region  Confirmed  Deaths  death_ratio
187          Yemen       2063     601     0.291323
152   Sierra Leone       2386      74     0.031014
72   Guinea-Bissau       2419      43     0.017776
172           Togo       2558      57     0.022283
26    Burkina Faso       2582      67     0.025949
..             ...        ...     ...          ...
141         Russia    1802762   30899     0.017140
62          France    1881171   42281     0.022476
23          Brazil    5726227  162922     0.028452
79           India    8636011  127571     0.014772
176             US   10331958  240316     0.023259

[152 rows x 4 columns]

In [67]:
df_final = df_filtered.sort_values(by="death_ratio")
df_final

    Country_Region  Confirmed  Deaths  death_ratio
153      Singapore      58073      28     0.000482
139          Qatar     134663     233     0.001730
161      Sri Lanka      14715      41     0.002786
108       Maldives      12030      41     0.003408
22        Botswana       7835      27     0.003446
..             ...        ...     ...          ...
52         Ecuador     175711   12849     0.073126
162          Sudan      14301    1116     0.078037
135           Peru     923527   87542     0.094791
114         Mexico     978531   95842     0.097945
187          Yemen       2063     601     0.291323

[152 rows x 4 columns]

In [69]:
number_of_keep_counts = int(len(df_final) * 0.20)
number_of_keep_counts

30

In [71]:
best_counts = df_final.iloc[:number_of_keep_counts].copy()
best_counts

           Country_Region  Confirmed  Deaths  death_ratio
153             Singapore      58073      28     0.000482
139                 Qatar     134663     233     0.001730
161             Sri Lanka      14715      41     0.002786
108              Maldives      12030      41     0.003408
22               Botswana       7835      27     0.003446
179  United Arab Emirates     144385     518     0.003588
12                Bahrain      83811     331     0.003949
45                 Cyprus       6098      27     0.004428
154              Slovakia      84347     390     0.004624
78                Iceland       5114      24     0.004693
122                 Nepal     199760    1148     0.005747
71                 Guinea      12484      74     0.005928
42          Cote d'Ivoire      20847     126     0.006044
93                 Kuwait     133381     821     0.006155
63                  Gabon       9029      57     0.006313
67                  Ghana      49302     320     0.006491
120            Mozambique      13892      99     0.007126
107              Malaysia      42050     300     0.007134
168            Tajikistan      11376      83     0.007296
142                Rwanda       5262      40     0.007602
97                Lebanon      96907     749     0.007729
65                Georgia      63650     521     0.008185
103            Luxembourg      23710     198     0.008351
102             Lithuania      27374     229     0.008366
84                 Israel     320811    2699     0.008413
182            Uzbekistan      69027     588     0.008518
184             Venezuela      95445     834     0.008738
186    West Bank and Gaza      59422     533     0.008970
177                Uganda      14704     133     0.009045
15                Belarus     108300    1016     0.009381

In [74]:
final_result = best_counts[["Country_Region" , "death_ratio"]]
final_result.shape

(30, 2)

In [75]:
final_result.to_csv("20percent.csv" , header=False)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به راهنمایی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [76]:
import zlib
import zipfile

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ["top10cases.csv", "recovery_rate.csv", "vsiran.csv", "20percent.csv", "covid19.ipynb"]
compress(file_names)

File Paths:
['top10cases.csv', 'recovery_rate.csv', 'vsiran.csv', '20percent.csv', 'covid19.ipynb']